### ISSUE TITLE
java.lang.IllegalArgumentException: URI is not hierarchical

### ISSUE THREAD

**Issue by Michael1907** [mfatihercik/dsm#10]
Hi, I'm trying to use this library according to documentation but no matter what path I use i get the same error as in title. For example :

DSMBuilder builder = new DSMBuilder("/tmp/targetFile.yaml");
DSM dsm = builder.setType(DSMBuilder.XML).create();

Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:418)
	at com.github.mfatihercik.dsb.resource.FileSystemResourceAccessor.addRootPath(FileSystemResourceAccessor.java:54)
	at com.github.mfatihercik.dsb.resource.AbstractResourceAccessor.init(AbstractResourceAccessor.java:39)
	at com.github.mfatihercik.dsb.resource.FileSystemResourceAccessor.init(FileSystemResourceAccessor.java:47)
	at com.github.mfatihercik.dsb.resource.FileSystemResourceAccessor.<init>(FileSystemResourceAccessor.java:27)
	at com.github.mfatihercik.dsb.configloader.AbstractConfigLoader.setResourceAccessor(AbstractConfigLoader.java:89)
	at com.github.mfatihercik.dsb.configloader.AbstractConfigLoader.<init>(AbstractConfigLoader.java:32)
	at com.github.mfatihercik.dsb.configloader.YamlConfigLoaderStrategy.<init>(YamlConfigLoaderStrategy.java:11)
	at com.github.mfatihercik.dsb.DSMBuilder.create(DSMBuilder.java:99)
	at com.github.mfatihercik.dsb.DSMBuilder.create(DSMBuilder.java:93)

I don't understand what the problem is, the path is correct and the file is present.

**Comment by mfatihercik** [comment]
Hi;

there is  a mistake in example at documentation. Sorry for that. 
you have to create java.util.File object and then create DSMBulder as shown below.

DSMBuilder builder = new DSMBuilder(**new File("/tmp/targetFile.yaml")**);
DSM dsm = builder.setType(DSMBuilder.XML).create();

if you pass a String  DSMBuilder accept this string as yaml configuration file.

**Comment by Michael1907** [comment]
Thank you.
